spring.application.name=user-service

# Подключение к БД
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Ascdfg56
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate настройки
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.enabled=true

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
app.kafka.notification-topic=user-notifications
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer



