server:
  port: 8081

spring:
  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: '*'
            type:
              mapping: ru.aston.homework04.dto.UserEvent:ru.aston.homework05.dto.UserEvent

  # Настройки почты
  mail:
    host: localhost
    port: 3025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false